name: wasm-wip

on:
  push:
    branches:
      - wasm

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: 'https://registry.npmjs.org/'
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Build
      id: build
      run: |
        cd rust/js
        npm run build
        npm pack
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: npm
        path: rust/js/evmole-*.tgz

  wheel:
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
        conf:
          - os: ubuntu-latest
            target: x86_64
          - os: windows-latest
            target: x86
          - os: macos-latest
            target: universal2-apple-darwin
    runs-on: ${{ matrix.conf.os }}
    steps:
      - uses: actions/checkout@v4
      - name: ${{ matrix.conf.target }} - py${{ matrix.python-version }}
        uses: PyO3/maturin-action@v1
        with:
          maturin-version: 1.7.0
          target: ${{ matrix.conf.target }}
          manylinux: auto
          args: -i ${{ matrix.python-version }} ${{ matrix.conf.os == 'ubuntu-latest' && matrix.python-version == '3.11' && '--sdist' || '' }} --release --out dist -m rust/Cargo.toml
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.conf.target }}-${{ matrix.python-version }}
          path: dist

  merge:
    runs-on: ubuntu-latest
    needs: [npm, wheel]
    steps:
       - name: Merge Artifacts
         uses: actions/upload-artifact/merge@v4
         with:
           name: artifacts
           delete-merged: true
